import dadReading from './assets/full_story/01_dad_reading.png'
import audreyGone from './assets/full_story/02_audrey_gone.png'
import emilyTransport from './assets/full_story/03_emily_transport.png'
import arrivalEnchantedLand from './assets/full_story/04_arrival_enchanted_land.png'
import animalFriends from './assets/full_story/08_animal_friends.png'
import castleNoDoor from './assets/full_story/09_castle_no_door.png'
import forestEntrance from './assets/full_story/10_forest_entrance.png'
import deepForest from './assets/full_story/11_deep_forest.png'
import forestMap from './assets/full_story/forest_map.png'
import witchHouse from './assets/full_story/12_witch_house.png'
import goldenKey from './assets/full_story/13_golden_key.png'
import keyEscape from './assets/full_story/14_key_escape.png'
import dragonCaveGate from './assets/full_story/15_dragon_cave_gate.png'
import dragonsSleeping from './assets/full_story/16_dragons_sleeping.png'
import dragonsAwaken from './assets/full_story/17_dragons_awaken.png'
import flightToCastle from './assets/full_story/18_flight_to_castle.png'
import towerBalcony from './assets/full_story/19_tower_balcony.png'
import audreyTower from './assets/full_story/20_audrey_tower.png'
import sistersReunited from './assets/full_story/21_sisters_reunited.png'
import freeAtLast from './assets/full_story/22_free_at_last.png'
import backInBed from './assets/full_story/25_back_in_bed.png'
import endScreen from './assets/full_story/27_end_screen.png'

export const BASE_SIZE = {
  width: 1024,
  height: 576,
}

const MAP_WITCH_CABIN_ZONES = [
  {
    x: 14,
    y: 6,
    width: 58,
    height: 18,
    hint: 'The witch is not hiding on the snowy mountain peaks.',
  },
  {
    x: 64,
    y: 28,
    width: 24,
    height: 30,
    hint: 'That path winds back toward the open meadows.',
  },
  {
    x: 40,
    y: 72,
    width: 28,
    height: 16,
    hint: 'We already passed the forest entrance. Look deeper into the woods.',
  },
  {
    x: 48,
    y: 20,
    width: 30,
    height: 22,
    hint: 'Only trees and moss here. Keep searching the map.',
  },
  {
    x: 10,
    y: 40,
    width: 16,
    height: 12,
    trail: true,
    hint: 'Good eye! The red dotted trail starts here. Follow it to the red X.',
  },
  {
    x: 27,
    y: 34,
    width: 20,
    height: 20,
    correct: true,
  },
]

export const STORY = [
  {
    image: endScreen,
    title: 'The Two Princesses',
    body: '',
    task: '',
    isMenu: true,
    backgroundAudio: 'menuMusic',
    backgroundVolume: 0.3,
    backgroundFadeOutMs: 2500,
  },
  {
    image: dadReading,
    title: 'Once Upon a Time',
    body: 'One evening, the two girls were tucked into bed, warm and cozy under a blanket with stars and moons. Their father David had just finished reading their favorite bedtime story. He kissed them both goodnight and said, “Good night, my two little princesses. I love you.” The room was filled with soft moonlight, and the only sound was the gentle rhythm of their breathing as they drifted off to sleep.',
    task: 'Turn off the lamp to go to sleep.',
    advanceOnTap: true,
    transition: 'dream',
    target: { x: 15, y: 200, width: 100, height: 125 },
  },
  {
    image: audreyGone,
    title: 'Where is Audrey?',
    body: 'But when the sun rose the next morning, something strange had happened. When Emily woke up and opened her eyes, she looked at the other side of the bed. Audrey was gone. Emily sat up and looked around the room. Everything was quiet—until something sparkled on the floor. She slid out of bed and tiptoed over.',
    task: 'Get the magic mirror and look inside.',
    imagePosition: 'center bottom',
    advanceOnTap: true,
    tapAudio: 'magicMirror',
    transition: 'fadeToBlack',
    target: { x: 825, y: 500, width: 170, height: 75 },
    done: 'Emily found a magic mirror on the floor—a beautiful, golden-framed mirror with swirls and tiny gems along the edges.',
  },
  {
    image: emilyTransport,
    title: 'What is this Mirror?',
    body: 'Emily picked up the mirror and said, “Where is Audrey?” Something happened. The mirror shimmered. Then, with a rush of wind and a swirl of light—WHOOSH!—Emily was swept away! She spun through sparkling clouds, floating stars, and beautiful colors.',
    task: 'Touch the castle in the mirror to start your adventure.',
    advanceOnTap: true,
    transition: 'video',
    tapVideo: 'emilyMirrorTransport',
    backgroundAudio: 'whisperingCastle',
    backgroundVolume: 0.2,
    backgroundFadeOutMs: 2000,
    target: { x: 575, y: 220, width: 50, height: 75 },
  },
  {
    image: arrivalEnchantedLand,
    title: 'The Enchanted Land',
    body: 'Suddenly, Emily landed in a magical enchanted land. Rolling meadows stretched out before her. Wildflowers danced in the wind. A silver stream trickled through the hills, and in the distance, high atop a mountain, stood a castle made of white stone with a blue roof. Its tallest tower touched the clouds. Emily began to walk down the path toward the castle.',
    task: 'Tap the path to walk toward the castle.',
    panelPosition: 'bottom-left',
    advanceOnTap: true,
    transition: 'video',
    tapVideo: 'emilyWalksPath',
    videoAdvance: 'fadeToBlack',
    target: { x: 575, y: 200, width: 175, height: 75 },
  },
  {
    image: animalFriends,
    title: 'New Friends',
    body: 'Along the way, Emily met the silliest, sweetest group of animals. There was a small yellow bear who loved honey, a gloomy gray donkey who sighed a lot, and a bouncy white rabbit with ears that didn’t quite match. They looked at Emily with big, curious eyes. “Have you seen my sister Audrey?” Emily asked. The bear licked honey off his paw and said, “We think… she was taken.” The donkey nodded. “By the witch,” he muttered. “The witch in the Great Forest,” said the rabbit, twitching his nose. “She locked Audrey up in the tower at the top of the mountain.” Emily looked up at the enormous castle. The wind blew. Her pink dress sparkled in the sun. She clenched the magic mirror close to her heart and said, “Then we have to rescue her.”',
    task: 'Tap each new friend to hear them talk.',
    panelPosition: 'top-right',
    introVideo: 'emilyMeetsFriends',
    introVideoAdvance: 'fadeToBlack',
    advanceOnTap: true,
    sequenceStepDelay: 3000,
    sequenceCompleteDelay: 5000,
    sequenceCompleteTransition: 'fadeToBlack',
    targetSequence: [
      {
        label: 'Tap Bear',
        audio: 'bear',
        target: { x: 540, y: 235, width: 124, height: 124 },
      },
      {
        label: 'Tap Donkey',
        audio: 'donkey',
        target: { x: 652, y: 150, width: 152, height: 172 },
      },
      {
        label: 'Tap Rabbit',
        audio: 'rabbit',
        target: { x: 768, y: 290, width: 126, height: 148 },
      },
    ],
  },
  {
    image: castleNoDoor,
    title: 'How to Get In?',
    body: 'Emily and her new animal friends set off across the hills toward the tall white castle. The path twisted through flower-filled meadows and glittering streams. When they reached the castle, they crossed the wide wooden drawbridge—but something was wrong. There was no door. No stairs. No way to get to the tower at the top. Emily searched every wall and every stone, but there seemed to be no way into the castle. “How can we rescue Audrey if we can’t even get inside?” Emily asked. The little yellow bear rubbed his belly and said, “There’s a legend about two flying dragons hidden deep in the Great Forest. Maybe they can help.”',
    task: 'Tap the tower balcony.',
    panelPosition: 'bottom-left',
    advanceOnTap: true,
    tapAudio: 'audreyRescue',
    advanceDelay: 6000,
    advanceVideo: 'audreyMapDrop',
    advanceTransition: 'fadeToBlack',
    waitingTask: 'Listen to Audrey...',
    target: { x: 610, y: 10, width: 125, height: 150 },
    done: 'Emily’s eyes lit up. “If we find them, one dragon can fly me to Audrey—and the other can bring her back!”',
  },
  {
    image: forestEntrance,
    title: 'Into the Forest',
    body: 'The animals seemed nervous. “The forest is dark,” said the donkey. “And deep,” said the bear. “And spooky,” added the rabbit. But Emily was very brave. “We have to try to find Audrey.” She opened Audrey’s map and looked for the way in. “There,” she said, pointing to the forest path. “That’s the way.”',
    task: 'Open the map and tap the forest path to enter bravely.',
    panelPosition: 'top-right',
    advanceOnTap: true,
    mapAccess: {
      mapImage: forestMap,
      mode: 'advance',
      targetOnly: true,
      mapAudio: 'scene7',
      transition: 'fadeToBlack',
      transitionDelay: 5000,
      solveMessage: 'This is the way into the Great Forest!',
      markers: {
        youAreHere: { x: 75, y: 50, offsetX: 55, offsetY: -92 },
        youAreHereLabel: 'You are here',
        destination: { x: 55, y: 74, offsetY: -375, hitRadius: 9 },
        destinationLabel: 'Forest path',
      },
      zones: [
        {
          x: 14,
          y: 6,
          width: 58,
          height: 18,
          hint: 'The forest entrance is farther south on the map.',
        },
        {
          x: 29,
          y: 42,
          width: 16,
          height: 16,
          hint: 'That is the witch’s cabin. First we need to enter the forest.',
        },
        {
          x: 64,
          y: 28,
          width: 24,
          height: 30,
          hint: 'That path leads back toward the meadows.',
        },
      ],
    },
    done: 'Emily traced the path with her finger. “This way into the Great Forest,” she said bravely.',
  },
  {
    image: deepForest,
    title: 'Follow the Map',
    body: 'The forest was quiet. Almost too quiet. Emily unfolded the crumpled map again. The bear leaned over her shoulder. “Look for the big red X,” he whispered. The donkey tapped the parchment with his hoof. “It leads to the witch’s cabin.” The rabbit twitched his nose. “I’m scared but let’s go that way.” Emily studied the winding paths, the forests, and felt brave. “That’s where the key to the dragon’s cave is so we have to go,” she said.',
    task: 'Open the map and find the witch’s cabin.',
    panelPosition: 'top-right',
    advanceOnTap: true,
    mapAccess: {
      mapImage: forestMap,
      mode: 'puzzle',
      mapAudio: 'scene7',
      transition: 'fadeToBlack',
      transitionDelay: 5000,
      solveMessage: "You found the witch's cabin!",
      markers: {
        youAreHere: { x: 55, y: 74, offsetY: -375 },
        youAreHereLabel: 'You are here',
        destination: { x: 37, y: 50, offsetY: -50 },
        destinationLabel: 'Witch\'s cabin',
      },
      zones: MAP_WITCH_CABIN_ZONES,
    },
    done: 'Emily pointed to the red X. “There it is—the witch’s cabin, hidden between the trees!” The animals cheered quietly. “Now we know where to go,” said the bear.',
  },
  {
    image: witchHouse,
    title: "The Witch's House",
    body: 'Then suddenly, ahead of them, they saw a soft orange glow. A crooked house stood between the trees. Smoke puffed from the chimney. Inside the window, they saw her—the witch. She stirred a bubbling cauldron. And right behind her, hanging on a hook, was a set of golden keys. “There it is—the key to the dragons’ cave,” whispered the bear.',
    task: 'Tap the cottage door.',
    backgroundAudio: 'eerieWhisper',
    backgroundVolume: 0.3,
    advanceOnTap: true,
    kenBurns: { variant: 'door', duration: 4000 },
    advanceDelay: 4000,
    advanceTransition: 'fadeToBlack',
    target: { x: 680, y: 255, width: 80, height: 90 },
    done: '“We’ll wait until the witch falls asleep,” Emily said. “Then I’ll sneak in and get the key.” The animals gulped.',
  },
  {
    image: goldenKey,
    title: 'The Golden Key',
    body: 'That night, when the forest was still, Emily tiptoed toward the house. She gently opened the door. But as she stepped forward—CREAAAK!—a loose floorboard made a noise. The witch started to move in her sleep. The sound was waking her up. Emily froze. Then… silence. The witch rolled over and seemed to fall back asleep.',
    task: 'Tap the golden keys.',
    panelPosition: 'bottom-left',
    backgroundAudio: 'woodCreak',
    backgroundVolume: 0.35,
    advanceOnTap: true,
    done: 'Emily grabbed the key and ran!',
    targetSequence: [
      {
        label: 'Tap the golden keys.',
        audio: 'witchVoice',
        target: { x: 700, y: 30, width: 90, height: 90 },
      },
      {
        label: 'Tap the door to rejoin your friends.',
        target: { x: 30, y: 90, width: 170, height: 400 },
      },
    ],
    sequenceCompleteDelay: 1000,
    sequenceCompleteTransition: 'fadeToBlack',
    sequenceStepWaitingTask: 'Sneak toward the door...',
  },
  {
    image: keyEscape,
    sceneVideo: 'keyEscape',
    sceneVideoMuted: true,
    sceneAudio: 'greatEscape',
    title: 'Run!',
    body: 'The door slammed shut behind her as the animals cheered, and they dashed toward the cave.',
    advanceOnTap: true,
    autoAdvanceOnVideoEnd: true,
    autoAdvanceTransition: 'fadeToBlack',
  },
  {
    image: dragonCaveGate,
    title: 'The Cave Gate',
    body: 'At the edge of the forest, hidden behind green ivy and stone, they found the cave—a huge round gated door carved into a rocky hill. Emily placed the key into the lock and turned it. Click. The door creaked open.',
    task: 'Tap the keyhole.',
    advanceOnTap: true,
    tapAudio: 'keyInsert',
    advanceDelay: 2000,
    target: { x: 630, y: 175, width: 85, height: 140 },
    done: 'Inside, the cave sparkled like diamonds.',
  },
  {
    image: dragonsSleeping,
    title: 'Sleeping Dragons',
    body: 'Two dragons lay sleeping on glowing crystal beds. One was pink. One was blue—just like Emily and Audrey’s dresses.',
    task: 'Tap the sleeping dragons.',
    backgroundAudioSet: ['dragonSleep1', 'dragonSleep2', 'dragonSleep3'],
    backgroundVolume: 0.35,
    backgroundAudioOptions: { sequential: true, minGapMs: 0, maxGapMs: 0, initialDelayMs: 0 },
    advanceOnTap: true,
    transition: 'video',
    tapVideo: 'dragonsAwakenGreet',
    videoAdvance: 'fadeToBlack',
    target: { x: 325, y: 325, width: 85, height: 85 },
    done: 'Their wings shimmered as they began to wake.',
  },
  {
    image: dragonsAwaken,
    title: 'Jax and Lily',
    body: 'The pink dragon opened her eyes. “You are brave,” she said in a kind voice to Emily. Emily stepped forward. “Can you help me rescue my sister Audrey from the tower?” The blue dragon stretched her wings. “Climb on,” she said to Emily. “We will take you to her.”',
    task: 'Tap the pink dragon to fly.',
    advanceOnTap: true,
    target: { x: 365, y: 85, width: 200, height: 200 },
  },
  {
    image: flightToCastle,
    title: 'Dragon Flight',
    body: 'The animals on the ground waved as Emily and the dragons soared into the sky. Higher and higher they flew, until the castle tower was just below.',
    task: 'Tap the castle to reach the tower.',
    advanceOnTap: true,
    transition: 'video',
    tapVideo: 'dragonFlightTower',
    panelPosition: 'bottom-left',
    target: { x: 750, y: 400, width: 125, height: 110 },
  },
  {
    image: towerBalcony,
    title: 'At the Tower',
    body: 'The pink dragon landed gently on the balcony. Emily climbed off and was so excited to see her sister again.',
    task: 'Tap the doorway to look inside.',
    advanceOnTap: true,
    target: { x: 925, y: 200, width: 100, height: 255 },
  },
  {
    image: audreyTower,
    title: 'Audrey!',
    body: '“Audrey!” she cried. Audrey looked up from her cushion by the window. “Emily! You found me!”',
    task: 'Tap Audrey.',
    advanceOnTap: true,
    transition: 'video',
    tapVideo: 'audreyReunion',
    tapVideoMuted: true,
    tapAudio: 'audreyReunionMusic',
    tapAudioVolume: 0.9,
    tapAudioCarryToNextScene: true,
    target: { x: 655, y: 260, width: 75, height: 100 },
    done: 'Outside, the blue dragon hovered at the balcony.',
  },
  {
    image: sistersReunited,
    title: 'Audrey Is Safe',
    body: 'They hugged, kissed, and spun around in laughter. The two sisters were reunited once again. “Come on,” Emily said. “Jax and Lily are outside and will fly us home.”',
    task: 'Tap the Balcony.',
    advanceOnTap: true,
    inheritsCarriedTapAudio: true,
    fadeCarriedTapAudioOnTap: true,
    fadeCarriedTapAudioMs: 2500,
    advanceTransition: 'fadeToBlack',
    target: { x: 25, y: 75, width: 150, height: 400 },
  },
  {
    image: freeAtLast,
    title: 'Free at Last',
    body: 'Emily and Audrey climbed onto the dragon’s back and were ready to fly home.',
    task: 'Tap the forest to fly home.',
    advanceOnTap: true,
    transition: 'video',
    tapVideo: 'flyHome',
    followUpVideo: 'flyHomeFinale',
    followUpVideoTransition: 'fadeToBlack',
    videoAdvance: 'fadeToBlack',
    target: { x: 100, y: 150, width: 150, height: 150
    
     },
  },
  {
    image: backInBed,
    title: 'The End',
    body: '',
    task: '',
    isEndScreen: true,
    finishFadeDuration: 4000,
  },
]
